spring:
  profiles:
    active: dev
  jackson:
    date-format: yyyy-MM-dd'T'HH:mm:ss.SSS'Z'
    time-zone: UTC
    default-property-inclusion: non_null

# Sa-Token
sa-token:
  token-name: Authorization
  token-prefix: Bearer
  timeout: 604800        # refresh token 7天（秒）
  active-timeout: 7200   # access token 2小时（秒）
  is-concurrent: true
  is-share: false
  token-style: uuid
  is-log: false

# Knife4j
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
knife4j:
  enable: true
  setting:
    language: zh_cn

# MyBatis-Plus
mybatis-plus:
  global-config:
    db-config:
      id-type: assign_id
      logic-delete-field: isDeleted
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
  mapper-locations: classpath:mapper/**/*.xml
